# dbt_project.yml

name: 'my_new_project'
version: '1.0.0'
config-version: 2

# Profil DBT à utiliser pour ce projet
profile: 'default'

# Chemins vers les différents types de fichiers
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # Répertoire qui stockera les fichiers SQL compilés
clean-targets:         # Répertoires à supprimer par `dbt clean`
  - "target"
  - "dbt_packages"

# Configuration des modèles
models:
  my_new_project:
    mart:
      +materialized: table  # Tous les modèles dans le dossier mart seront matérialisés sous forme de table
      finance:
        +schema: finance   # Les modèles dans le sous-dossier finance utiliseront le schéma finance
