version: 2

sources:
  - name: gz_raw_data
    schema: gz_raw_data  # Replace with the actual schema name
    tables:
      - name: raw_gz_product
        description: "Table containing raw product data from Greenweez."
        columns:
          - name: products_id
            description: "Unique identifier for each product."
            tests:
              - unique
              - not_null
          - name: purchse_price
            description: "Original column name for purchase price, to be corrected to 'purchase_price'."
          - name: purchase_price
            description: "Purchase price of the product, converted to FLOAT64."
      
      - name: raw_gz_ship
        description: "Table containing raw shipping data, including order IDs and shipping costs."
        columns:
          - name: orders_id
            description: "Unique identifier for each order."
            tests:
              - unique
              - not_null
          - name: shipping_fee
            description: "Fee charged for shipping."
          - name: shipping_fee_1
            description: "Alternative shipping fee column, to be compared with 'shipping_fee'."
          - name: ship_cost
            description: "Shipping cost, converted to FLOAT64."
      
      - name: raw_gz_sales
        description: "Table containing sales data from Greenweez. Each row represents a 'product_id' found in an 'orders_id'."
        columns:
          - name: date_date
            description: "Date of purchase."
          - name: orders_id
            description: "Unique identifier for each order."
          - name: pdt_id
            description: "Original product ID, later renamed to 'products_id'."
          - name: products_id
            description: "Renamed product ID."
          - name: revenue
            description: "Revenue generated from the sale."
          - name: quantity
            description: "Quantity of products sold."




